---
name: Package Docker

env:
  DOCKERHUB_REPOSITORY: i73v/nos-build-machine

on:
  push:
    branches:
      - 'main'

jobs:
  package-docker:
    name: Package Docker
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:docker"
          load: true
          tags: "${{ env.DOCKERHUB_REPOSITORY }}:test"
          
      - name: Test Image
        run: |
          docker run --rm ${{ env.DOCKERHUB_REPOSITORY }}:test

      - name: Push Image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:docker"
          push: true
          tags: "${{ env.DOCKERHUB_REPOSITORY }}:latest, ${{ env.DOCKERHUB_REPOSITORY }}:${{ github.sha }}"
          labels: "nos.build-machine.llvm=16, theos.build-machine.github.sha=${{ github.sha }}"
